// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC5eKr8wZRCx7KX_WQt1S9jR40ML_vTTyQ',
    appId: '1:92670418386:web:aeca65ca4c8fe00fab3c0b',
    messagingSenderId: '92670418386',
    projectId: 'u6-pa1',
    authDomain: 'u6-pa1.firebaseapp.com',
    databaseURL: 'https://u6-pa1-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'u6-pa1.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCDsLoskxmp3xz9CG2FZGxiKQhzqic20Zo',
    appId: '1:92670418386:android:32b3c7bc0ee16d2bab3c0b',
    messagingSenderId: '92670418386',
    projectId: 'u6-pa1',
    databaseURL: 'https://u6-pa1-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'u6-pa1.firebasestorage.app',
  );

}